export const countryDialCodes = [
  { country: "أفغانستان", code: "+93" },
  { country: "ألبانيا", code: "+355" },
  { country: "ألمانيا", code: "+49" },
  { country: "أندورا", code: "+376" },
  { country: "أنغولا", code: "+244" },
  { country: "أنتيغوا وباربودا", code: "+1268" },
  { country: "الأرجنتين", code: "+54" },
  { country: "أرمينيا", code: "+374" },
  { country: "أستراليا", code: "+61" },
  { country: "النمسا", code: "+43" },
  { country: "أذربيجان", code: "+994" },
  { country: "البهاما", code: "+1242" },
  { country: "البحرين", code: "+973" },
  { country: "بنغلاديش", code: "+880" },
  { country: "باربادوس", code: "+1246" },
  { country: "بيلاروس", code: "+375" },
  { country: "بلجيكا", code: "+32" },
  { country: "بليز", code: "+501" },
  { country: "بنين", code: "+229" },
  { country: "بوتان", code: "+975" },
  { country: "بوليفيا", code: "+591" },
  { country: "البوسنة والهرسك", code: "+387" },
  { country: "بوتسوانا", code: "+267" },
  { country: "البرازيل", code: "+55" },
  { country: "بروناي", code: "+673" },
  { country: "بلغاريا", code: "+359" },
  { country: "بوركينا فاسو", code: "+226" },
  { country: "بوروندي", code: "+257" },
  { country: "كمبوديا", code: "+855" },
  { country: "الكاميرون", code: "+237" },
  { country: "كندا", code: "+1" },
  { country: "الرأس الأخضر", code: "+238" },
  { country: "جمهورية أفريقيا الوسطى", code: "+236" },
  { country: "تشاد", code: "+235" },
  { country: "تشيلي", code: "+56" },
  { country: "الصين", code: "+86" },
  { country: "كولومبيا", code: "+57" },
  { country: "جزر القمر", code: "+269" },
  { country: "الكونغو", code: "+242" },
  { country: "جمهورية الكونغو الديمقراطية", code: "+243" },
  { country: "كوستاريكا", code: "+506" },
  { country: "ساحل العاج", code: "+225" },
  { country: "كرواتيا", code: "+385" },
  { country: "كوبا", code: "+53" },
  { country: "قبرص", code: "+357" },
  { country: "التشيك", code: "+420" },
  { country: "الدنمارك", code: "+45" },
  { country: "جيبوتي", code: "+253" },
  { country: "دومينيكا", code: "+1767" },
  { country: "جمهورية الدومينيكان", code: "+1809" },
  { country: "الإكوادور", code: "+593" },
  { country: "مصر", code: "+20" },
  { country: "السلفادور", code: "+503" },
  { country: "غينيا الاستوائية", code: "+240" },
  { country: "إريتريا", code: "+291" },
  { country: "إستونيا", code: "+372" },
  { country: "إسواتيني", code: "+268" },
  { country: "إثيوبيا", code: "+251" },
  { country: "فيجي", code: "+679" },
  { country: "فنلندا", code: "+358" },
  { country: "فرنسا", code: "+33" },
  { country: "الغابون", code: "+241" },
  { country: "غامبيا", code: "+220" },
  { country: "جورجيا", code: "+995" },
  { country: "غانا", code: "+233" },
  { country: "اليونان", code: "+30" },
  { country: "غرينادا", code: "+1473" },
  { country: "غواتيمالا", code: "+502" },
  { country: "غينيا", code: "+224" },
  { country: "غينيا بيساو", code: "+245" },
  { country: "غيانا", code: "+592" },
  { country: "هايتي", code: "+509" },
  { country: "هندوراس", code: "+504" },
  { country: "المجر", code: "+36" },
  { country: "آيسلندا", code: "+354" },
  { country: "الهند", code: "+91" },
  { country: "إندونيسيا", code: "+62" },
  { country: "إيران", code: "+98" },
  { country: "العراق", code: "+964" },
  { country: "أيرلندا", code: "+353" },
  { country: "إيطاليا", code: "+39" },
  { country: "جامايكا", code: "+1876" },
  { country: "اليابان", code: "+81" },
  { country: "الأردن", code: "+962" },
  { country: "كازاخستان", code: "+7" },
  { country: "كينيا", code: "+254" },
  { country: "كيريباتي", code: "+686" },
  { country: "الكويت", code: "+965" },
  { country: "قيرغيزستان", code: "+996" },
  { country: "لاوس", code: "+856" },
  { country: "لاتفيا", code: "+371" },
  { country: "لبنان", code: "+961" },
  { country: "ليسوتو", code: "+266" },
  { country: "ليبيريا", code: "+231" },
  { country: "ليبيا", code: "+218" },
  { country: "ليختنشتاين", code: "+423" },
  { country: "ليتوانيا", code: "+370" },
  { country: "لوكسمبورغ", code: "+352" },
  { country: "مدغشقر", code: "+261" },
  { country: "مالاوي", code: "+265" },
  { country: "ماليزيا", code: "+60" },
  { country: "جزر المالديف", code: "+960" },
  { country: "مالي", code: "+223" },
  { country: "مالطا", code: "+356" },
  { country: "جزر مارشال", code: "+692" },
  { country: "موريتانيا", code: "+222" },
  { country: "موريشيوس", code: "+230" },
  { country: "المكسيك", code: "+52" },
  { country: "ميكرونيزيا", code: "+691" },
  { country: "مولدوفا", code: "+373" },
  { country: "موناكو", code: "+377" },
  { country: "منغوليا", code: "+976" },
  { country: "الجبل الأسود", code: "+382" },
  { country: "المغرب", code: "+212" },
  { country: "موزمبيق", code: "+258" },
  { country: "ميانمار", code: "+95" },
  { country: "ناميبيا", code: "+264" },
  { country: "ناورو", code: "+674" },
  { country: "نيبال", code: "+977" },
  { country: "هولندا", code: "+31" },
  { country: "نيوزيلندا", code: "+64" },
  { country: "نيكاراغوا", code: "+505" },
  { country: "النيجر", code: "+227" },
  { country: "نيجيريا", code: "+234" },
  { country: "كوريا الشمالية", code: "+850" },
  { country: "مقدونيا الشمالية", code: "+389" },
  { country: "النرويج", code: "+47" },
  { country: "عمان", code: "+968" },
  { country: "باكستان", code: "+92" },
  { country: "بالاو", code: "+680" },
  { country: "فلسطين", code: "+970" },
  { country: "بنما", code: "+507" },
  { country: "بابوا غينيا الجديدة", code: "+675" },
  { country: "باراغواي", code: "+595" },
  { country: "بيرو", code: "+51" },
  { country: "الفلبين", code: "+63" },
  { country: "بولندا", code: "+48" },
  { country: "البرتغال", code: "+351" },
  { country: "قطر", code: "+974" },
  { country: "رومانيا", code: "+40" },
  { country: "روسيا", code: "+7" },
  { country: "رواندا", code: "+250" },
  { country: "سانت كيتس ونيفيس", code: "+1869" },
  { country: "سانت لوسيا", code: "+1758" },
  { country: "سانت فنسنت والغرينادين", code: "+1784" },
  { country: "ساموا", code: "+685" },
  { country: "سان مارينو", code: "+378" },
  { country: "ساو تومي وبرينسيبي", code: "+239" },
  { country: "المملكة العربية السعودية", code: "+966" },
  { country: "السنغال", code: "+221" },
  { country: "صربيا", code: "+381" },
  { country: "سيشل", code: "+248" },
  { country: "سيراليون", code: "+232" },
  { country: "سنغافورة", code: "+65" },
  { country: "سلوفاكيا", code: "+421" },
  { country: "سلوفينيا", code: "+386" },
  { country: "جزر سليمان", code: "+677" },
  { country: "الصومال", code: "+252" },
  { country: "جنوب أفريقيا", code: "+27" },
  { country: "كوريا الجنوبية", code: "+82" },
  { country: "جنوب السودان", code: "+211" },
  { country: "إسبانيا", code: "+34" },
  { country: "سريلانكا", code: "+94" },
  { country: "السودان", code: "+249" },
  { country: "سورينام", code: "+597" },
  { country: "السويد", code: "+46" },
  { country: "سويسرا", code: "+41" },
  { country: "سوريا", code: "+963" },
  { country: "طاجيكستان", code: "+992" },
  { country: "تنزانيا", code: "+255" },
  { country: "تايلاند", code: "+66" },
  { country: "تيمور الشرقية", code: "+670" },
  { country: "توغو", code: "+228" },
  { country: "تونغا", code: "+676" },
  { country: "ترينيداد وتوباغو", code: "+1868" },
  { country: "تونس", code: "+216" },
  { country: "تركيا", code: "+90" },
  { country: "تركمانستان", code: "+993" },
  { country: "توفالو", code: "+688" },
  { country: "أوغندا", code: "+256" },
  { country: "أوكرانيا", code: "+380" },
  { country: "الإمارات العربية المتحدة", code: "+971" },
  { country: "المملكة المتحدة", code: "+44" },
  { country: "الولايات المتحدة الأمريكية", code: "+1" },
  { country: "أوروغواي", code: "+598" },
  { country: "أوزبكستان", code: "+998" },
  { country: "فانواتو", code: "+678" },
  { country: "الفاتيكان", code: "+39" },
  { country: "فنزويلا", code: "+58" },
  { country: "فيتنام", code: "+84" },
  { country: "اليمن", code: "+967" },
  { country: "زامبيا", code: "+260" },
  { country: "زيمبابوي", code: "+263" },
] as const;

export type CountryDialCode = (typeof countryDialCodes)[number];
